# Scrapping Characters Names from Wiki Fandom Page using Selenium 
- Data Manipulation and Cleaning

In [1]:
import numpy as np 
import pandas as pd
from selenium import webdriver
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.common.by import By

In [2]:
driver = webdriver.Chrome(ChromeDriverManager().install())

C:\Users\Aaron\AppData\Local\Temp\ipykernel_155408\1503906442.py:1: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(ChromeDriverManager().install())

In [3]:
url = 'https://chaoswalking.fandom.com/wiki/Category:Characters'
driver.get(url)

In [4]:
character_elements = driver.find_elements(By.CLASS_NAME,'category-page__member-link')
characters = []
for name in character_elements:
    characters.append(name.text)
characters

['1017',
 'Aaron',
 'Acorn',
 'Category:Antagonists',
 'Category:Battlemores',
 'Ben Moore',
 'Bradley Tench',
 'Cillian Boyd',
 'Corinne Wyatt',
 'David Prentiss',
 'David Prentiss, Jr.',
 'Category:Deceased',
 'Category:Dogs',
 'Category:Females',
 'Healers',
 'Category:Horses',
 'Category:Humans',
 'Ivan Farrow',
 'Jackson Snow',
 'Jessica Elizabeth',
 'Lee',
 'Category:LGBT+',
 'Madeleine Poole',
 'Category:Males',
 'Manchee',
 'Mathidle',
 'Mr. Hammar',
 'Mr. Hewitt',
 'Mrs. Hewitt',
 'Nicola Coyle',
 'River Spackle',
 'Simone Watkin',
 'Category:Spackle',
 'Tam',
 'Category:The Answer',
 'Category:The Ask',
 'The Burden',
 'The Sky (character)',
 'Todd Hewitt',
 'Viola Eade',
 'Wilf']

In [5]:
## Filter out elements that contain a category of characters
categories = list(filter(lambda x: 'Category' in x.text, character_elements))
categories

[<selenium.webdriver.remote.webelement.WebElement (session="28f073616d2ee8c8740fce7cbed2102e", element="6f539476-6e43-4211-9e4d-bc7abfe531df")>,
 <selenium.webdriver.remote.webelement.WebElement (session="28f073616d2ee8c8740fce7cbed2102e", element="1894d05c-e101-4a4a-85bd-4dfb217e318a")>,
 <selenium.webdriver.remote.webelement.WebElement (session="28f073616d2ee8c8740fce7cbed2102e", element="a25d7f8d-f538-4761-85a4-e30a0c9e8a25")>,
 <selenium.webdriver.remote.webelement.WebElement (session="28f073616d2ee8c8740fce7cbed2102e", element="9cc72172-89ee-4ffb-9d66-05e6c9824049")>,
 <selenium.webdriver.remote.webelement.WebElement (session="28f073616d2ee8c8740fce7cbed2102e", element="4098be86-29cd-4326-b219-38731ab84bd3")>,
 <selenium.webdriver.remote.webelement.WebElement (session="28f073616d2ee8c8740fce7cbed2102e", element="5ee59f1b-5149-40e5-bfa4-da7a329314ac")>,
 <selenium.webdriver.remote.webelement.WebElement (session="28f073616d2ee8c8740fce7cbed2102e", element="dfa12cb2-0f7a-412e-a712-d5ba1d3f86d1")>,
 <selenium.webdriver.remote.webelement.WebElement (session="28f073616d2ee8c8740fce7cbed2102e", element="6800ca6b-9cbb-4d60-b0bb-821e9eeaaf69")>,
 <selenium.webdriver.remote.webelement.WebElement (session="28f073616d2ee8c8740fce7cbed2102e", element="89a71c23-e606-4bc2-8c21-8cd6a2aa440e")>,
 <selenium.webdriver.remote.webelement.WebElement (session="28f073616d2ee8c8740fce7cbed2102e", element="e85a44c7-5e39-40f6-9bc2-5b04e8256f85")>,
 <selenium.webdriver.remote.webelement.WebElement (session="28f073616d2ee8c8740fce7cbed2102e", element="91a5635f-3c9b-4d87-9601-1087abe7b8ac")>,
 <selenium.webdriver.remote.webelement.WebElement (session="28f073616d2ee8c8740fce7cbed2102e", element="6335d956-d42b-47b8-801e-ca748813667f")>]

In [6]:
## Collecting the href for each category
category_dict = {}
for category in categories:
    category_url = category.get_attribute('href')
    category_name = category.text
    category_dict[category_name] = category_url  
category_dict

{'Category:Antagonists': 'https://chaoswalking.fandom.com/wiki/Category:Antagonists',
 'Category:Battlemores': 'https://chaoswalking.fandom.com/wiki/Category:Battlemores',
 'Category:Deceased': 'https://chaoswalking.fandom.com/wiki/Category:Deceased',
 'Category:Dogs': 'https://chaoswalking.fandom.com/wiki/Category:Dogs',
 'Category:Females': 'https://chaoswalking.fandom.com/wiki/Category:Females',
 'Category:Horses': 'https://chaoswalking.fandom.com/wiki/Category:Horses',
 'Category:Humans': 'https://chaoswalking.fandom.com/wiki/Category:Humans',
 'Category:LGBT+': 'https://chaoswalking.fandom.com/wiki/Category:LGBT%2B',
 'Category:Males': 'https://chaoswalking.fandom.com/wiki/Category:Males',
 'Category:Spackle': 'https://chaoswalking.fandom.com/wiki/Category:Spackle',
 'Category:The Answer': 'https://chaoswalking.fandom.com/wiki/Category:The_Answer',
 'Category:The Ask': 'https://chaoswalking.fandom.com/wiki/Category:The_Ask'}

In [7]:
# Scraping each character in each category
for links in category_dict.keys():
    driver.get(category_dict[links])
    for name in driver.find_elements(By.CLASS_NAME,'category-page__member-link'):
        characters.append(name.text)

In [8]:
characters

['1017',
 'Aaron',
 'Acorn',
 'Category:Antagonists',
 'Category:Battlemores',
 'Ben Moore',
 'Bradley Tench',
 'Cillian Boyd',
 'Corinne Wyatt',
 'David Prentiss',
 'David Prentiss, Jr.',
 'Category:Deceased',
 'Category:Dogs',
 'Category:Females',
 'Healers',
 'Category:Horses',
 'Category:Humans',
 'Ivan Farrow',
 'Jackson Snow',
 'Jessica Elizabeth',
 'Lee',
 'Category:LGBT+',
 'Madeleine Poole',
 'Category:Males',
 'Manchee',
 'Mathidle',
 'Mr. Hammar',
 'Mr. Hewitt',
 'Mrs. Hewitt',
 'Nicola Coyle',
 'River Spackle',
 'Simone Watkin',
 'Category:Spackle',
 'Tam',
 'Category:The Answer',
 'Category:The Ask',
 'The Burden',
 'The Sky (character)',
 'Todd Hewitt',
 'Viola Eade',
 'Wilf',
 'Mr. Hammar',
 'The Ask',
 "Ben's Battlemore",
 "The Sky's Battlemore",
 '0038',
 'Aaron',
 'Acorn',
 'Cillian Boyd',
 'Con Ledger',
 'Corinne Wyatt',
 'David Prentiss',
 'David Prentiss, Jr.',
 'Duncan',
 'Fergal',
 'Francia',
 'Ivan Farrow',
 'Jackson Snow',
 'Jacob Snow',
 'James',
 'Jessica Elizabeth',
 'Madeleine Poole',
 'Manchee',
 'Mathidle',
 'Morpeth',
 'Mr. Hewitt',
 'Mrs. Hewitt',
 'Nicola Coyle',
 'River Spackle',
 'Simone Watkin',
 'The Burden',
 'The Sky (character)',
 "The Sky's Battlemore",
 'Whiskey',
 'Manchee',
 '0001',
 '1485',
 'Angharrad',
 'Corinne Wyatt',
 'Francia',
 'Healers',
 'Jane',
 'Jess',
 'Jessica Elizabeth',
 'Mathidle',
 'Mrs. Hewitt',
 'Nicola Coyle',
 'Simone Watkin',
 'Viola Eade',
 'Acorn',
 'Angharrad',
 'Morpeth',
 'Whiskey',
 '1485',
 'Aaron',
 'Ben Moore',
 'Bradley Tench',
 'Cillian Boyd',
 'Con Ledger',
 'Corinne Wyatt',
 'David Prentiss',
 'David Prentiss, Jr.',
 'Duncan',
 'Fergal',
 'Francia',
 'Healers',
 'Ivan Farrow',
 'Jackson Snow',
 'Jacob Snow',
 'James',
 'Jane',
 'Jess',
 'Jessica Elizabeth',
 'Lee',
 'Magnus',
 'Mathidle',
 'Matthew Lyle',
 'Mr. Hammar',
 'Mr. Hewitt',
 'Mrs. Hewitt',
 'Nicola Coyle',
 'Simone Watkin',
 'Tam',
 'Todd Hewitt',
 'Viola Eade',
 'Wilf',
 '1017',
 'Ben Moore',
 'Cillian Boyd',
 '0038',
 '1017',
 'Acorn',
 'Ben Moore',
 'Bradley Tench',
 'Cillian Boyd',
 'Con Ledger',
 'David Prentiss',
 'David Prentiss, Jr.',
 'Duncan',
 'Fergal',
 'Ivan Farrow',
 'Jackson Snow',
 'Jacob Snow',
 'James',
 'Lee',
 'Magnus',
 'Manchee',
 'Matthew Lyle',
 'Morpeth',
 'Mr. Hammar',
 'Mr. Hewitt',
 'Tam',
 'The Sky (character)',
 'Todd Hewitt',
 'Whiskey',
 'Wilf',
 '0001',
 '0038',
 '1017',
 'Ben Moore',
 'River Spackle',
 'The Burden',
 'The Pathways',
 'The Sky (character)',
 'The Sky (position)',
 'Ivan Farrow',
 'Nicola Coyle',
 'Viola Eade',
 'David Prentiss',
 'David Prentiss, Jr.',
 'Ivan Farrow',
 'Mr. Hammar',
 'Todd Hewitt']

In [10]:
characters_dict = {'Names' : characters}
characters_dict

{'Names': ['1017',
  'Aaron',
  'Acorn',
  'Category:Antagonists',
  'Category:Battlemores',
  'Ben Moore',
  'Bradley Tench',
  'Cillian Boyd',
  'Corinne Wyatt',
  'David Prentiss',
  'David Prentiss, Jr.',
  'Category:Deceased',
  'Category:Dogs',
  'Category:Females',
  'Healers',
  'Category:Horses',
  'Category:Humans',
  'Ivan Farrow',
  'Jackson Snow',
  'Jessica Elizabeth',
  'Lee',
  'Category:LGBT+',
  'Madeleine Poole',
  'Category:Males',
  'Manchee',
  'Mathidle',
  'Mr. Hammar',
  'Mr. Hewitt',
  'Mrs. Hewitt',
  'Nicola Coyle',
  'River Spackle',
  'Simone Watkin',
  'Category:Spackle',
  'Tam',
  'Category:The Answer',
  'Category:The Ask',
  'The Burden',
  'The Sky (character)',
  'Todd Hewitt',
  'Viola Eade',
  'Wilf',
  'Mr. Hammar',
  'The Ask',
  "Ben's Battlemore",
  "The Sky's Battlemore",
  '0038',
  'Aaron',
  'Acorn',
  'Cillian Boyd',
  'Con Ledger',
  'Corinne Wyatt',
  'David Prentiss',
  'David Prentiss, Jr.',
  'Duncan',
  'Fergal',
  'Francia',
  'Ivan Farrow',
  'Jackson Snow',
  'Jacob Snow',
  'James',
  'Jessica Elizabeth',
  'Madeleine Poole',
  'Manchee',
  'Mathidle',
  'Morpeth',
  'Mr. Hewitt',
  'Mrs. Hewitt',
  'Nicola Coyle',
  'River Spackle',
  'Simone Watkin',
  'The Burden',
  'The Sky (character)',
  "The Sky's Battlemore",
  'Whiskey',
  'Manchee',
  '0001',
  '1485',
  'Angharrad',
  'Corinne Wyatt',
  'Francia',
  'Healers',
  'Jane',
  'Jess',
  'Jessica Elizabeth',
  'Mathidle',
  'Mrs. Hewitt',
  'Nicola Coyle',
  'Simone Watkin',
  'Viola Eade',
  'Acorn',
  'Angharrad',
  'Morpeth',
  'Whiskey',
  '1485',
  'Aaron',
  'Ben Moore',
  'Bradley Tench',
  'Cillian Boyd',
  'Con Ledger',
  'Corinne Wyatt',
  'David Prentiss',
  'David Prentiss, Jr.',
  'Duncan',
  'Fergal',
  'Francia',
  'Healers',
  'Ivan Farrow',
  'Jackson Snow',
  'Jacob Snow',
  'James',
  'Jane',
  'Jess',
  'Jessica Elizabeth',
  'Lee',
  'Magnus',
  'Mathidle',
  'Matthew Lyle',
  'Mr. Hammar',
  'Mr. Hewitt',
  'Mrs. Hewitt',
  'Nicola Coyle',
  'Simone Watkin',
  'Tam',
  'Todd Hewitt',
  'Viola Eade',
  'Wilf',
  '1017',
  'Ben Moore',
  'Cillian Boyd',
  '0038',
  '1017',
  'Acorn',
  'Ben Moore',
  'Bradley Tench',
  'Cillian Boyd',
  'Con Ledger',
  'David Prentiss',
  'David Prentiss, Jr.',
  'Duncan',
  'Fergal',
  'Ivan Farrow',
  'Jackson Snow',
  'Jacob Snow',
  'James',
  'Lee',
  'Magnus',
  'Manchee',
  'Matthew Lyle',
  'Morpeth',
  'Mr. Hammar',
  'Mr. Hewitt',
  'Tam',
  'The Sky (character)',
  'Todd Hewitt',
  'Whiskey',
  'Wilf',
  '0001',
  '0038',
  '1017',
  'Ben Moore',
  'River Spackle',
  'The Burden',
  'The Pathways',
  'The Sky (character)',
  'The Sky (position)',
  'Ivan Farrow',
  'Nicola Coyle',
  'Viola Eade',
  'David Prentiss',
  'David Prentiss, Jr.',
  'Ivan Farrow',
  'Mr. Hammar',
  'Todd Hewitt']}

In [12]:
## Dropping duplicate names and removing categories
characters_df1 = pd.DataFrame(characters_dict)
characters_df1 = characters_df1[characters_df1['Names'].str.contains('Category') == False] 
characters_df1 = characters_df1.drop_duplicates()
characters_df1.replace('David Prentiss', 'Mayor')

                    Names
0                    1017
1                   Aaron
2                   Acorn
5               Ben Moore
6           Bradley Tench
7            Cillian Boyd
8           Corinne Wyatt
9                   Mayor
10    David Prentiss, Jr.
14                Healers
17            Ivan Farrow
18           Jackson Snow
19      Jessica Elizabeth
20                    Lee
22        Madeleine Poole
24                Manchee
25               Mathidle
26             Mr. Hammar
27             Mr. Hewitt
28            Mrs. Hewitt
29           Nicola Coyle
30          River Spackle
31          Simone Watkin
33                    Tam
36             The Burden
37    The Sky (character)
38            Todd Hewitt
39             Viola Eade
40                   Wilf
42                The Ask
43       Ben's Battlemore
44   The Sky's Battlemore
45                   0038
49             Con Ledger
53                 Duncan
54                 Fergal
55                Francia
58             Jacob Snow
59                  James
64                Morpeth
73                Whiskey
75                   0001
76                   1485
77              Angharrad
81                   Jane
82                   Jess
114                Magnus
116          Matthew Lyle
162          The Pathways
164    The Sky (position)

In [14]:
## Removing unwanted punctuation and splitting first names into seperate column
import re
characters_df1['Names'] = characters_df1['Names'].apply(lambda x: re.sub("[\(].*?[\)]", '', x))
characters_df1['First Name'] = characters_df1['Names'].apply(lambda x: x.split(' ')[0])
characters_df1['First Name'] = characters_df1['Names'].apply(lambda x: x if any(re.findall(r'Mr|Mrs|The', x)) else x.split()[0])

characters_df1

                    Names            First Name
0                    1017                  1017
1                   Aaron                 Aaron
2                   Acorn                 Acorn
5               Ben Moore                   Ben
6           Bradley Tench               Bradley
7            Cillian Boyd               Cillian
8           Corinne Wyatt               Corinne
9          David Prentiss                 David
10    David Prentiss, Jr.                 David
14                Healers               Healers
17            Ivan Farrow                  Ivan
18           Jackson Snow               Jackson
19      Jessica Elizabeth               Jessica
20                    Lee                   Lee
22        Madeleine Poole             Madeleine
24                Manchee               Manchee
25               Mathidle              Mathidle
26             Mr. Hammar            Mr. Hammar
27             Mr. Hewitt            Mr. Hewitt
28            Mrs. Hewitt           Mrs. Hewitt
29           Nicola Coyle                Nicola
30          River Spackle                 River
31          Simone Watkin                Simone
33                    Tam                   Tam
36             The Burden            The Burden
37               The Sky               The Sky
38            Todd Hewitt                  Todd
39             Viola Eade                 Viola
40                   Wilf                  Wilf
42                The Ask               The Ask
43       Ben's Battlemore                 Ben's
44   The Sky's Battlemore  The Sky's Battlemore
45                   0038                  0038
49             Con Ledger                   Con
53                 Duncan                Duncan
54                 Fergal                Fergal
55                Francia               Francia
58             Jacob Snow                 Jacob
59                  James                 James
64                Morpeth               Morpeth
73                Whiskey               Whiskey
75                   0001                  0001
76                   1485                  1485
77              Angharrad             Angharrad
81                   Jane                  Jane
82                   Jess                  Jess
114                Magnus                Magnus
116          Matthew Lyle               Matthew
162          The Pathways          The Pathways
164              The Sky               The Sky

In [15]:
## Exporting Dataframe into csv file
characters_df1.to_csv('characters.csv')

In [29]:
characters_df1

                                                 Names       First Name
0                                               Albert           Albert
4                                                 Amar             Amar
5                                                  Amy              Amy
6                                         Andrew Prior           Andrew
7                                         Anne Erasmus             Anne
..                                                 ...              ...
205              User blog:Mrlazy/My Choosing Ceremony             User
210  Which Divergent Faction Do You Belong In? —Epi...            Which
223                                             Connor           Connor
244                              File:Stark23969 1.JPG  File:Stark23969
305                                     Four's Stories           Four's

[81 rows x 2 columns]